import type { Metadata } from "next";
import { ADLaM_Display } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
import Link from "next/link";
// import { usePathname } from "next/navigation";
const inter = ADLaM_Display({ subsets: ["latin"],weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const defaultRoutes = ['/','/visitors']

export default function RootLayout({
  children,
  team,
  analytics
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode,
  analytics: React.ReactNode,
}>) {
  // const userPath = usePathname();
  // const show = defaultRoutes.includes(userPath)
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <AntdRegistry>
          <div className="container mx-auto" >
            <>            
              <div className="flex justify-center text-blue-500 p-6 gap-6" >
                <Link href="/" >Home</Link>
                <Link href="/visitors">Visitors</Link>
              </div> 
              <div className="flex justify-center gap-6">
                {team}
                {analytics}
              </div>
            </>

            {children}
          </div>
        </AntdRegistry>

      </body>
    </html>
  );
}
