import type { Metadata } from "next";
import { ADLaM_Display } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
const inter = ADLaM_Display({ subsets: ["latin"],weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      > 
        <AntdRegistry>
          {children}
          {modal}
        </AntdRegistry>

      </body>
    </html>
  );
}
